### ISSUE TITLE
Icon fonts not loading on latest AUR version

### ISSUE THREAD

**Issue by dinoshauer** [krypt-n/bar#10]
Hey just upgraded `lemonbar-xft-git` - Now fonts don't load as they used to.
Before the upgrade loading fonts like this worked, but not anymore.

```
lemonbar -p -f "Oxygen Mono-15","Icons-17","FontAwesome-17"
```

I tried reading the code but couldn't find anything after a quick glance, did I miss something or is this a new bug?

The following would usually output hi with a speaker icon:

```
echo "hi" | lemonbar -p -f "Oxygen Mono-15","Icons-17","FontAwesome-17"
```

EDIT: Added example with glyph

**Comment by krypt-n** [comment]
It is a breaking change introduced by merging 7880eac8c9b15810a2089ca8636b3d51d433a4b4 from upstream.
Instead of using

```
 lemonbar -p -f "Oxygen Mono-15","Icons-17","FontAwesome-17"
```

we'd now need to use

```
lemonbar -p -f "Oxygen Mono-15" -f "Icons-17" -f "FontAwesome-17"
```

This change was made by lemonboy because apparently some fonts have commas in their names.

**Comment by dinoshauer** [comment]
Beautiful, thanks. Makes a lot more sense as well :)
