### ISSUE TITLE
So, what's the proper way to specify an XFT font?

### ISSUE THREAD

**Issue by oatberry** [krypt-n/bar#13]
What's the syntax, will spaces throw it off, how do I give the size, etc... I'm recovering from XFLDs, heh

thanks!

**Comment by krypt-n** [comment]
You can use the `-f` flag to specify a font. Use multiple `-f`s for multiple fonts.
`-f Icons` for example.
If the name of the font contains a space, you have to put it in quotes: `-f "Dejavu Sans"`.
You can specify a font size by appending `-SIZE` to the fontname:
`-f Icons-8` or `-f "Dejavu Sans-10"`

**Comment by oatberry** [comment]
Thank you!
