### ISSUE TITLE
Xlib-xcb dependency

### ISSUE THREAD

**Issue by Talor-A** [krypt-n/bar#15]
make fails with this error:

``` bash
/bar>make
cc -Wall -std=c99 -Os -DVERSION="\"020a3e1\"" -I/usr/include/freetype2 -o lemonbar.o -c lemonbar.c
lemonbar.c:19:26: fatal error: X11/Xlib-xcb.h: No such file or directory
 #include <X11/Xlib-xcb.h>
                          ^
compilation terminated.
make: *** [lemonbar.o] Error 1
```

Lemonbar is already installed, so what additional dependencies does this fork need?

**Comment by krypt-n** [comment]
`X11/Xlib-xcb.h` is part of the `libX11` package on Arch Linux. Please check if there exists an equivalent package on your distribution.

**Comment by chrisshroba** [comment]
In case it helps anyone else, this worked for me (I'm sure most of these are unnecessary, sorry!):
sudo apt-get install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
