### ISSUE TITLE
Documenting xft options

### ISSUE THREAD

**Issue by Chrysostomus** [krypt-n/bar#17]
I think it would be good to document xft related options, like how to pass fonts in xft form or how to turn on antialiasing. I had to google the former from other places, and still have no idea how to do latter.

**Comment by krypt-n** [comment]
See [this list](http://www.freedesktop.org/software/fontconfig/fontconfig-user.html) of fontconfig options for selecting a font. I don't think we need to document anything there, if we mention that this fork accepts fontconfig specifiers.

**Comment by Chrysostomus** [comment]
Thanks for the info =)
