### ISSUE TITLE
Scroll buttons are unresponsive, A4 and A5

### ISSUE THREAD

**Issue by a-laptop** [krypt-n/bar#18]
Bound actions to buttons A1-3 are as expected but A4 and A5 are unresponsive, xev returns A4 and A5 button presses as expected. Tested with synaptics touch pad, logitech g300 and g402.

**Comment by krypt-n** [comment]
That is a bug that exists upstream aswell (LemonBoy/bar#154). I will look into it

**Comment by krypt-n** [comment]
Should be fixed in this fork. I opened a PR to fix it in LemonBoy's version.
