### ISSUE TITLE
Formatting does not seem to work

### ISSUE THREAD

**Issue by MadsRC** [krypt-n/bar#31]
The latest version (pulled yesterday) does not seem to support formatting. The problem seems to be that `%` isn't caught (As I don't have to use %% to get a literal percent sign as the man page states you should).

It should be reproduce-able with this command:
`echo "test" | lemonbar %{c} -g 2550x14 -B #ff00ff -F #FFFFFF -p`

The `%{c}` should center the text, however it does not seem to do that.

**Comment by krypt-n** [comment]
The formatting options are not passed to lemonbar as arguments, they are included in the input. Try

```
echo "%{c}test" | lemonbar -g 2550x14 -B #ff00ff -F #FFFFFF -p
```
