### ISSUE TITLE
Ability to specify `-o` for each font separately

### ISSUE THREAD

**Issue by rr-** [krypt-n/bar#8]
While I'd like to use a Powerline font for the cool triangles, I'd like to be able to use regular (unpatched) font for the text. Since these fonts have very different baselines, it would make sense to make `-o` able to handle them separately.

**Comment by krypt-n** [comment]
My idea for this would be that `-o` with one value applies to all fonts and `-o` with a comma seperated list of values applies the nth value of the list to the nth font.

I will probably look into implementing that tomorrow

**Comment by rr-** [comment]
Please note that in recent version of lemonbar fonts are specified in separate parameters like this:

```
-f FONT1 -f FONT2
```

rather than

```
-f FONT1,FONT2
```

but honestly, any way to achieve this would be nice. Thanks.

**Comment by krypt-n** [comment]
Implemented in c9f1425.
I merged the upstream `-f` change and `-o` now behaves similarly, although I dont like that the order in which parameters appear matters.
The first `-o` sets the offset for all fonts (including the first), the second for the second font, the third for the third font and so on.
